version: '3'
services:
    php:
      build:
        context: ./images/php
      volumes:
        - ./www:/var/www
      environment:
        XDEBUG_CONFIG: "remote_host=127.0.0.1 remote_enable=1 remote_autostart=off remote_port=9008"
        PHP_IDE_CONFIG: "serverName=tasks-test"
    nginx:
      image: nginx
      volumes:
        - ./images/php/hosts:/etc/nginx/conf.d
        - ./www:/var/www
        - ./logs:/var/log/nginx
      ports:
        - "8080:80"
      depends_on:
        - php
    db:
      image: postgres
      working_dir: /application
      volumes:
        - .:/application
      restart: always
      environment:
        POSTGRES_PASSWORD: password
